### ISSUE TITLE
'bun build' doesn't work out of the box

### ISSUE THREAD

**Issue by 3obby** [RubricLab/rubric#7]
using 'npm run build' works fine in the meantime! Currently, 'bun build' results in:

```
bun build v1.0.6 (969da088)
error: Missing entrypoints. What would you like to bundle?

Usage: bun build [flags] [...entrypoints]
```

**Comment by DexterStorey** [comment]
@3obby I think this is not supported with bun and not in our control, - specifically `bun build` takes mandatory arguments and doesn't run your default build command. I agree this is a bit frustrating for our use case (since bun install, bun start, bun dev work oob) but I wonder if there's a good reason...

You could look into posting an issue here: https://github.com/oven-sh/bun/issues

Closing for now - can re-open if anyone finds a way to alias it internally.
